@baseURL=http://localhost:8080/api

@token=eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbkBhZG1pbi5jb20iLCJpYXQiOjE3NzkwMDE2MTYsImV4cCI6MTc3OTAwMzQxNn0.ORX_8cMQCLYjJF4yhiBDJhAicRBDiZAzv7NTKPB6gksCoN9yGu3bjg8tUFuDMrjo

POST {{baseURL}}/auth/login
Content-Type: application/json

{
    "email": "admin@admin.com",
    "password": "adminadmin"
}

### Create User
POST {{baseURL}}/user
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "user 2",
    "email": "use2@gmail.com",
    "password": "strongpwd"
}

### View all users
GET {{baseURL}}/user/view-all

### Grand Admin Role
PUT {{baseURL}}/user/grand-admin?userId=3
Authorization: Bearer {{token}}
