@baseURL=http://localhost:8080/api

@token=eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJhZG1pbkBhZG1pbi5jb20iLCJpYXQiOjE3Nzg4Njg0NDIsImV4cCI6MTc3ODg2ODYyMn0.BwWgxwXKan5Z73bvOe9OAzMHsUVyChFEr7tH6JudxjKSMgoGtcadQGfRUlTQBYVL

POST {{baseURL}}/auth/login
Content-Type: application/json

{
    "email": "admin@admin.com",
    "password": "adminadmin"
}

### Create User
POST {{baseURL}}/user/create
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "user 1",
    "email": "user@gmail.com",
    "password": "strongpwd"
}

### View all users
GET {{baseURL}}/user/view-all
Authorization: Bearer {{token}}

### Grand Admin Role
PUT {{baseURL}}/user/grand-admin?userId=2
Authorization: Bearer {{token}}
